### ISSUE TITLE
[Feature request] Add second argument to `change` event callback

### ISSUE THREAD

**Issue by gustavoaz7** [mengxiong10/vue-datepicker-next#1]
**What problem does this feature solve?**
Mimics vue2-datapicker API more precisely;
Allows us to know which type of change triggered the event

**What does the proposed API look like?**
Same as in vue2-datapicker: https://github.com/mengxiong10/vue2-datepicker#events
[`change` event] `Callback Arguemnts: date, type('date'|'hour'|'minute'|'second'|'ampm')`

**Comment by mengxiong10** [comment]
v.1.0.2 add it.
