### ISSUE TITLE
[Bug] Initial v-model:value doesn't work with date library

### ISSUE THREAD

**Issue by rscbeplus** [mengxiong10/vue-datepicker-next#10]
**"vue-datepicker-next":** "^1.0.2"
**"vue":** "^3.0.0",
**Browser**: All of them

Thank you very much for providing this calendar libary! 

**Steps to reproduce**

1. Visit: https://vue-vg3x9m.stackblitz.io
2. See Start/Enddate
3. But range is not selected in Calendar
![Bildschirmfoto 2022-03-04 um 18 49 11](https://user-images.githubusercontent.com/95248858/156815481-7400c1dc-e975-4c33-b883-0330034ab23f.png)

**Reproduction Link or Source Code**
https://stackblitz.com/edit/vue-vg3x9m?file=src/App.vue

**Expected behavior**
A set value in the v-model:value should set the calendar range selected in the Calendar.

**Actual behavior**
Range is only set by manual clicking and not preset values.
I saw the events, especially the _update:value_, but have no clue if this will help in my case as value does not change initially.

**Comment by mengxiong10** [comment]
Because `dayjs()` is not a `Date Object` , you should use `toDate`.
```js
      timerange: [
        dayjs().isoWeekday(1).toDate(),
        dayjs().isoWeekday(7).toDate(),
      ],

```

**Comment by robinschreiner** [comment]
Thanks for taking the time! 
Hadn't thought about that and feel dumb now. 🤦‍♂️
