### ISSUE TITLE
[Bug] Getting 'v-model' directives require no argument on Nuxt

### ISSUE THREAD

**Issue by kossa** [mengxiong10/vue-datepicker-next#13]
**Vue2-datepicker version**: 1.0.2
**Vue version**: nuxt 2.15(vue2)
**Browser**: Opera 85.0.4341.18

**Steps to reproduce**
Install nuxt js, and then install [vue-datepicker-next](https://github.com/mengxiong10/vue-datepicker-next)

**Actual behavior**
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1175584/160229113-82caa54a-286b-40e5-93af-ea33e658dea5.png">

**Comment by mengxiong10** [comment]
`vue-datepicker-next` is for vue3.
`nuxt 2` doesn't support `vue3`.
You should use `vue2-datepicker` not `vue-datepicker-next`

**Comment by kossa** [comment]
Thank you
