### ISSUE TITLE
Possibility to set max diff between range calendars

### ISSUE THREAD

**Issue by MskHelen17** [mengxiong10/vue-datepicker-next#14]
Hello!
In the [vue2-datepicker](https://github.com/mengxiong10/vue2-datepicker) package there is a possibility to set max difference between calendars in range mode:
```
Datepicker.CalendarRange.computed.calendarMaxDiff = function () {
    return 1;
};
```
As a result, when I scroll through, for example, the left calendar, the right one is scrolled simultaneously with it. And the difference between them is always 1 month. This is very convenient for me

There is no such computed property in [vue3 version](https://github.com/mengxiong10/vue-datepicker-next/blob/main/lib/calendar/CalendarRange.tsx) of CalendarRange file anymore. And I haven't found another way to achieve this behavior.

It would be great if such an opportunity appeared in the package for vue3. Thank you in advance!

**Comment by mengxiong10** [comment]
The recommended way is to use a prop calendar.
```html
<date-picker :calendar="calendar" @calendar-change="handleCalendarChange" />
```
```js
data() {
  return {
     caledar: [new Date(), new Date()]
  }
},
methods: {
   handleCalendarChange(dates, index) {
     // update dates
     .....
     this.calendar = dates
   }
}

```

**Comment by MskHelen17** [comment]
Yes, everything worked out with calendar prop. Thanks!

**Comment by theDevelopper** [comment]
Can you add this prop to the documentation?
