### ISSUE TITLE
format属性可否增加函数类型？

### ISSUE THREAD

**Issue by okssq** [mengxiong10/vue-datepicker-next#21]
**What problem does this feature solve?**
现在用到了周选择器，
当我选择了例如06-29至07-04这一周时，
我希望input面板上的显示值为2022-06-29 ~ 2022-07-04，或者根据date自定义显示内容，现在无法实现这个功能~~

**What does the proposed API look like?**

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue-datepicker-next#formatter
使用 formatter
```html
<date-picker :formatter="formatter" />
```
```js
data() {
    return {
      formatter: {
       stringify: (date) => {
        const firstDate = ''
        const endDate = ''
        return  `${firstDate} ~ ${endDate}`
      }
      }
    }
}
```

**Comment by okssq** [comment]
> https://github.com/mengxiong10/vue-datepicker-next#formatter 使用 formatter
> 
> ```
> <date-picker :formatter="formatter" />
> ```
> 
> ```js
> data() {
>     return {
>       formatter: {
>        stringify: (date) => {
>           const firstDate = ''
>           const endDate = ''
>           return  `${firstDate} ~ ${endDate}`
>         }
>       }
>     }
> }
> ```

这个更改的日期面板上的显示把，我需要的是格式化一个显示input内容的函数~

**Comment by mengxiong10** [comment]
@okssq 这个就是input 内容的显示

**Comment by okssq** [comment]
> 这个就是input 内容的显示
好的谢谢，因为我试了下getWeek:  (  ) => 1 , 日期面板上的week都是显示1~
