### ISSUE TITLE
The number of the week is not correct according to ISO-8601

### ISSUE THREAD

**Issue by diegocontreras2** [mengxiong10/vue-datepicker-next#22]
The calendar week number is not correct according to ISO 8601.
Week 1 should be January 3, 2022 but in the calendar week 1 is the last week of December 2021.

For uses of filters in my database it does not work for me because the week is advanced in your calendar.

[https://espanol.epochconverter.com/semanas/2022#:~:text=La%20semana%20comienza%20el%20d%C3%ADa,la%20semana%20actual%20es%2033.](url)

![image](https://user-images.githubusercontent.com/42698568/184679971-92a70612-31ad-4ab7-b7ff-6584b302c63a.png)

**Comment by mengxiong10** [comment]
You can use `getWeek` function.
https://github.com/mengxiong10/vue-datepicker-next#formatter
