### ISSUE TITLE
vue3.2.39最新版本引入使用即报错[Bug]

### ISSUE THREAD

**Issue by okssq** [mengxiong10/vue-datepicker-next#24]
**Vue2-datepicker version**:
**Vue version**:
**Browser**:

**Steps to reproduce**

**Reproduction Link or Source Code**

**Expected behavior**

**Actual behavior**

**Comment by mengxiong10** [comment]
@okssq 具体什么错误？ 我测试了没问题

**Comment by okssq** [comment]
![image](https://user-images.githubusercontent.com/52643522/191152244-aa3f99f1-1808-46fa-9ed6-e90f620b5fdd.png)
![image](https://user-images.githubusercontent.com/52643522/191152320-df57b941-d9d6-4c81-aa4b-b38fee7c6d90.png)
![image](https://user-images.githubusercontent.com/52643522/191152412-8f730f06-6f38-4e69-aa84-ead08da6a207.png)

只要引用了组件就报错，删掉代码就正常~

**Comment by mengxiong10** [comment]
<date-picker /> 换成 <DatePicker />

**Comment by okssq** [comment]
> >

还是不行~

**Comment by mengxiong10** [comment]
暂时不清楚， 不用 script setup 是可以的

**Comment by okssq** [comment]
> 

在script setup里面导出吗？

**Comment by mengxiong10** [comment]
@okssq  对

**Comment by zuo305** [comment]
不好意思，我遇到同样的问题，请问具体是怎么解决的，能给更详细一点吗？我没看懂，什么叫“在script setup”里面导出？

**Comment by mengxiong10** [comment]
@zuo305 具体是什么错误，还有代码是怎么样？ 生产版本才有问题，感觉和 vue 有关系

**Comment by zuo305** [comment]
Hi @mengxiong10  ， 这个是错误截图，我的VUE 版本是3.2.47. 嗯，我这个确实很奇怪，我印象中上个月还是没有问题的，最近突然发现出错了。
![Screenshot 2023-03-05 104950](https://user-images.githubusercontent.com/4032158/222934192-ff243fcd-0de5-49fc-ae07-9643bb7fd05c.jpg)
![Screenshot 2023-03-05 104950](https://user-images.githubusercontent.com/4032158/222934200-4fd0d393-6a5d-4b2f-8c44-bd472ba13849.jpg)

**Comment by zuo305** [comment]
![Screenshot 2023-03-05 105005](https://user-images.githubusercontent.com/4032158/222934267-da5ea80e-ab48-4cb6-bd8c-342222106b13.jpg)

**Comment by zuo305** [comment]
Hi, @mengxiong10 I also tried the most simple code but got the same error.

<script>
  import DatePicker from 'vue-datepicker-next';
  import 'vue-datepicker-next/index.css';

  export default {
    components: { DatePicker },
    data() {
      return {
        time0: null,
      };
    },
  };
</script>

<template>
  <div>
    <date-picker v-model:value="time0"></date-picker>
  </div>
</template>
