### ISSUE TITLE
[Question] Is there a contribution guide?

### ISSUE THREAD

**Issue by MrMohamedAbdallah** [mengxiong10/vue-datepicker-next#27]
I tried to clone the repo and run it on my machine but got several errors.
First error got solved by updating Vite.
Now Vite is running but still having an error on the homepage.

Is there a contribution guide? or an installation steps?

Thanks for the awesome package.

**Comment by mengxiong10** [comment]
There are no other requirements, you can try use node > 16.

**Comment by mengxiong10** [comment]
What's the error? Maybe you can remove the package-lock.json and node_modules, then npm install.

**Comment by MrMohamedAbdallah** [comment]
@mengxiong10 Thanks, when I removed the package-lock.json node_modules and tried again it worked. I wonder, will the changes in the package-lock.json be accepted?
