### ISSUE TITLE
[Bug] Step options  for time picker doesn't work.

### ISSUE THREAD

**Issue by crypteo** [mengxiong10/vue-datepicker-next#29]
**Vue2-datepicker version**: 1.0.2
**Vue version**: 3.2.26
**Browser**: Any

Hey, I think there is a problem with the step options;
If I use minuteStep="10", I can choose only 0 or 10
If I use minuteStep="5", I can choose 0, 5 or 55 ???

https://codesandbox.io/s/datepicker-pmmcfl

**Comment by mengxiong10** [comment]
use `number` not `string`
```html
<date-picker type="time" :minuteStep="5" format="HH:mm" />
```
