### ISSUE TITLE
[Question] Is there any way to imperatively close picker?

### ISSUE THREAD

**Issue by jinyongp** [mengxiong10/vue-datepicker-next#35]
**Vue-datepicker-next version**: 1.0.2
**Vue version**: 3.2.45
**Browser**: Chrome (110.0.5481.100)

I found an issue(https://github.com/mengxiong10/vue-datepicker-next/issues/34) related to this problem, but I think the "closePopup" function disappeared. Is there any other way?

**Comment by mengxiong10** [comment]
You can use prop `open`.
```html
<date-picker :open="open" @open="handleOpen" @close="handleClose" />
```
```js
data() {
    return { open: false }
},
methods: {
  handleOpen() { this.open = true },
  handleClose() { this.open = false }
}

```

**Comment by jinyongp** [comment]
It works well, thanks!
