### ISSUE TITLE
我可以单独使用这个面板吗，我需要自定义

### ISSUE THREAD

**Issue by vela666** [mengxiong10/vue-datepicker-next#48]
![image](https://github.com/mengxiong10/vue-datepicker-next/assets/69613314/68f2f029-a4d5-4f47-a3aa-9bb61bb7cad0)

类似自定义成这样的效果
![image](https://github.com/mengxiong10/vue-datepicker-next/assets/69613314/c37af0b6-8cc3-44bc-8500-d87874599f5f)

**Comment by mengxiong10** [comment]
可以，你可以使用
```js
import DatePicker from 'vue-datepicker-next'

const {Calendar,
  CalendarRange,
  TimePanel,
  TimeRange,
  DateTime,
  DateTimeRange } = DatePicker

```

**Comment by cnjm** [comment]
请问有单个日期面板，但是可以选日期范围的吗
