### ISSUE TITLE
[Feature request] Option to Display Single Calendar when using "range" for Intra-month Date Selection

### ISSUE THREAD

**Issue by dankozz1t** [mengxiong10/vue-datepicker-next#50]
**Feature Request:**
I would like to request the addition of a new option in the DatePicker component to control the number of calendars displayed when using the "range" option. Currently, when the "range" option is enabled, two calendars are displayed side by side. However, I have a specific use case where I need to select a date range within the same month, and displaying two calendars is not optimal for this scenario.

**Expected Behavior:**
I propose adding a new option, such as singleCalendar, that, when set to true, will display only one calendar when the "range" option is used. This way, users can easily select a date range within the same month without the clutter of two calendars.

**Environment:**
Vue-datepicker-next version: 1.0.3
Browser: Google Chome 114.0.5735.199
Operating System: Windows 11

**Note:**
I understand that the current behavior of displaying two calendars is useful for selecting date ranges spanning across multiple months. However, the proposed singleCalendar option would be beneficial for cases where intra-month date selection is required. This feature enhancement would improve the usability and flexibility of the DatePicker component.

**Expected Outcome:**
With the singleCalendar option set to true and the disabled-date method notBeforeTodayAndOnlyThisMonth implemented, the DatePicker component will display only one calendar when using the "range" option. Additionally, it will allow users to select dates only from the current day and within the current month. This ensures that only valid dates within the same month can be chosen and eliminates the issue of displaying two calendars.

```js
<DatePicker
  type="date"
  format="YYYY-MM-DD"
  valueType="format"
  placeholder="YYYY-MM-DD ~ YYYY-MM-DD"
  v-model:value="date"
  range
  :singleCalendar="true"
 :disabled-date="(date) => notBeforeTodayAndOnlyThisMonth(date, currentMonth)"
></DatePicker>


methods: {
  notBeforeTodayAndOnlyThisMonth(date, currentMonth) {
    const startOfMonth = new Date(date.getFullYear(), currentMonth, 1);
    const endOfMonth = new Date(date.getFullYear(), currentMonth + 1, 0);

    return !(date >= startOfMonth && date <= endOfMonth);
  },
},

```

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/range-picker-with-one-calendar-jvv5s?file=/src/App.vue

**Comment by dankozz1t** [comment]
> 

Thank you very much for your attention, but I need the same solution but for Vue 3. I am using your library "vue-datepicker-next.". Not "vue2-datepicker"


```js
 "vue": "3.2.47",
 "vue-datepicker-next": "1.0.3"
```

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/range-picker-with-one-calendar-3sxhnq?file=/src/App.vue:128-137
They have almost the same api

**Comment by dankozz1t** [comment]
Thank you very much, this solves my problem!
