### ISSUE TITLE
[Feature request] Restore use of inline

### ISSUE THREAD

**Issue by jeroenbreen** [mengxiong10/vue-datepicker-next#7]
Just as in vue2-datepicker, can we have the `inline` prop be restored?

**Comment by jeroenbreen** [comment]
ah, just found out about `append-to-body`

**Comment by aislanmaia** [comment]
@jeroenbreen `append-to-body` seems not work!!
Do you have any options ?

Use `Calendar` component as suggested in another thread seems doesnt work with range functionality !

**Comment by aislanmaia** [comment]
Oh I see that exists a `CalendarRange` component that makes the trick!!

**Comment by Boluwatife2904** [comment]
UPDATE: I already got the solution from the issues raised. Many Thanks 🙌🏽

@mengxiong10 please how can I make the calendar inline. I can't seem to get it to work. 

I was able to do something like this in the vue2-datepicker using the inline: true prop

<img width="939" alt="Screenshot 2023-04-17 at 06 12 55" src="https://user-images.githubusercontent.com/49585353/232384397-a19db9d6-5a77-4e46-9d16-c16d13b6764a.png">


I am trying to replicate using vue-datepicker-next.

<img width="681" alt="Screenshot 2023-04-17 at 06 12 01" src="https://user-images.githubusercontent.com/49585353/232384327-cabecb1d-8a65-4b7b-89ce-788be6d0f708.png">


Many thanks.

**Comment by mengxiong10** [comment]
use `Calendar ` component
```js
const Calendar = Datepicker.Calendar
```

```html
<calendar />
```
